[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "d2d4fb365c39883e2279197cd9c5d3d51715a6df"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Notify]
+ Added option to display repair toast (enabled by default)

[Misc]
+ Added last unlockable sector
"""
