[plugin]
repository = "https://github.com/Kirrana/xivlauncher_physics_plugin.git"
commit = "34d517340be9295ff2ec919bc8a8fb2e3008b8f3"
owners = ["Kirrana"]
project_path = "SamplePlugin"
changelog = "Adds support for skipping 2,3,4,5 frames instead of only 2"