[plugin]
repository = "https://github.com/itsbexy/gaugeomatic.git"
commit = "3e381a510885a6d169294de74d5fc6e59aa5a838"
owners = [
    "ItsBexy",
]
changelog = """
This update should fix an issue with the latest client patch, which was causing crashes for BLM players using the plugin.

## WIDGETS
- The *Simple Gems* widget has been updated with a variety of new shapes to choose from!

## TWEAKS
- **New Tweak for MNK:** Reverse the order of the icons on your Beast Chakra Gauge
- **Temporarily Disabled:** VPR's color-coding tweak has been temporarily disabled, as it needs to be adapted for the Gauge's updated behaviour.

## MISC
- The names and timers for the recently-changed VPR statuses and actions have been updated accordingly. (I may have missed some things, will review when less sleepy.)
"""
